platform :ios, '12.0'

target 'JianChi' do
  use_frameworks!

  # Pods for JianChi

  target 'JianChiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JianChiUITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'Parchment'

end
